spring:
  profiles.active: dev
  datasource:
    url : jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
    separator : $$
    initialize: true
    sql-script-encoding: UTF-8
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:  
      ddl-auto : none
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
      time-zone : GMT+8
      date-format : yyyy-MM-dd HH:mm:ss
      
flowable:
  databaseSchemaUpdate : true #create-drop create false
  idm.enabled : false
  databaseSchema : plumdo_flow


logging:
  config: classpath:logback-spring.xml

server:
  port : 8082
    
         